# Generated by Django 3.2.7 on 2021-09-30 09:27

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_profile_nick_name'),
        ('beauty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nama anonim kamu : ')),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Komentar')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='backend.post', verbose_name='Post Yang Dikomentar')),
            ],
        ),
    ]
